import type { Rng } from "./prng";

export type Place = {
  neighborhood: string;
  city: string;
  zip: string;
  county: string;
  lat: number;
  lng: number;
  weight: number; // ~ how many listings cluster here
  priceTier: 1 | 2 | 3; // 1 modest, 3 premium
  community: "planned_cdd" | "hoa" | "established"; // drives HOA/CDD
  waterChance: number; // probability a listing here is waterfront (→ flood zone)
};

// Real central-Florida neighborhoods with approximate centers. (Facts only — no steering.)
export const PLACES: readonly Place[] = [
  {
    neighborhood: "Winter Park",
    city: "Winter Park",
    zip: "32789",
    county: "Orange",
    lat: 28.599,
    lng: -81.3392,
    weight: 10,
    priceTier: 3,
    community: "established",
    waterChance: 0.25,
  },
  {
    neighborhood: "Lake Nona",
    city: "Orlando",
    zip: "32827",
    county: "Orange",
    lat: 28.3736,
    lng: -81.2469,
    weight: 10,
    priceTier: 2,
    community: "planned_cdd",
    waterChance: 0.1,
  },
  {
    neighborhood: "Baldwin Park",
    city: "Orlando",
    zip: "32814",
    county: "Orange",
    lat: 28.564,
    lng: -81.329,
    weight: 8,
    priceTier: 2,
    community: "hoa",
    waterChance: 0.1,
  },
  {
    neighborhood: "Dr. Phillips",
    city: "Orlando",
    zip: "32819",
    county: "Orange",
    lat: 28.4502,
    lng: -81.4912,
    weight: 8,
    priceTier: 2,
    community: "hoa",
    waterChance: 0.15,
  },
  {
    neighborhood: "Windermere",
    city: "Windermere",
    zip: "34786",
    county: "Orange",
    lat: 28.4955,
    lng: -81.5348,
    weight: 8,
    priceTier: 3,
    community: "hoa",
    waterChance: 0.4,
  },
  {
    neighborhood: "Horizon West",
    city: "Winter Garden",
    zip: "34787",
    county: "Orange",
    lat: 28.5653,
    lng: -81.5862,
    weight: 9,
    priceTier: 2,
    community: "planned_cdd",
    waterChance: 0.1,
  },
  {
    neighborhood: "Celebration",
    city: "Celebration",
    zip: "34747",
    county: "Osceola",
    lat: 28.3253,
    lng: -81.5331,
    weight: 7,
    priceTier: 2,
    community: "planned_cdd",
    waterChance: 0.1,
  },
  {
    neighborhood: "Kissimmee",
    city: "Kissimmee",
    zip: "34741",
    county: "Osceola",
    lat: 28.292,
    lng: -81.4076,
    weight: 7,
    priceTier: 1,
    community: "established",
    waterChance: 0.15,
  },
  {
    neighborhood: "Lake Mary",
    city: "Lake Mary",
    zip: "32746",
    county: "Seminole",
    lat: 28.7589,
    lng: -81.3178,
    weight: 7,
    priceTier: 2,
    community: "hoa",
    waterChance: 0.15,
  },
  {
    neighborhood: "Oviedo",
    city: "Oviedo",
    zip: "32765",
    county: "Seminole",
    lat: 28.67,
    lng: -81.208,
    weight: 6,
    priceTier: 2,
    community: "hoa",
    waterChance: 0.1,
  },
  {
    neighborhood: "Maitland",
    city: "Maitland",
    zip: "32751",
    county: "Orange",
    lat: 28.6278,
    lng: -81.3631,
    weight: 5,
    priceTier: 2,
    community: "established",
    waterChance: 0.2,
  },
  {
    neighborhood: "Clermont",
    city: "Clermont",
    zip: "34711",
    county: "Lake",
    lat: 28.5494,
    lng: -81.7729,
    weight: 6,
    priceTier: 1,
    community: "established",
    waterChance: 0.3,
  },
  {
    neighborhood: "Davenport",
    city: "Davenport",
    zip: "33837",
    county: "Polk",
    lat: 28.1614,
    lng: -81.602,
    weight: 7,
    priceTier: 1,
    community: "planned_cdd",
    waterChance: 0.1,
  },
  {
    neighborhood: "Sanford",
    city: "Sanford",
    zip: "32771",
    county: "Seminole",
    lat: 28.8003,
    lng: -81.2733,
    weight: 5,
    priceTier: 1,
    community: "established",
    waterChance: 0.25,
  },
  {
    neighborhood: "St. Cloud",
    city: "St. Cloud",
    zip: "34769",
    county: "Osceola",
    lat: 28.2489,
    lng: -81.2812,
    weight: 5,
    priceTier: 1,
    community: "established",
    waterChance: 0.15,
  },
  {
    neighborhood: "Winter Springs",
    city: "Winter Springs",
    zip: "32708",
    county: "Seminole",
    lat: 28.6989,
    lng: -81.2937,
    weight: 5,
    priceTier: 2,
    community: "hoa",
    waterChance: 0.1,
  },
];

/** Jitter ~±1.5km around the place center so map pins cluster realistically. */
export function jitterCoord(place: Place, rng: Rng): [number, number] {
  const lng = place.lng + rng.float(-0.018, 0.018, 6);
  const lat = place.lat + rng.float(-0.018, 0.018, 6);
  return [lng, lat];
}
