import type { NewQualificationQuestion } from "../schema/qualification-questions";

// Seeded Carolina-style defaults (ADR-007). Nilyan edits these in /admin/questions (D11).
// Facts/logistics only — no steering.
export const QUESTIONS: NewQualificationQuestion[] = [
  // BUY
  {
    intent: "buy",
    key: "timeline",
    sortOrder: 1,
    type: "single_select",
    required: true,
    label: "When are you looking to buy?",
    labelEs: "¿Cuándo planeas comprar?",
    options: [
      { value: "0_3", label: "0–3 months", labelEs: "0–3 meses" },
      { value: "3_6", label: "3–6 months", labelEs: "3–6 meses" },
      { value: "6_12", label: "6–12 months", labelEs: "6–12 meses" },
      { value: "browsing", label: "Just browsing", labelEs: "Solo explorando" },
    ],
  },
  {
    intent: "buy",
    key: "budget",
    sortOrder: 2,
    type: "single_select",
    required: true,
    label: "What is your budget?",
    labelEs: "¿Cuál es tu presupuesto?",
    options: [
      { value: "u300", label: "Under $300k", labelEs: "Menos de $300k" },
      { value: "300_500", label: "$300k–$500k", labelEs: "$300k–$500k" },
      { value: "500_800", label: "$500k–$800k", labelEs: "$500k–$800k" },
      { value: "800p", label: "$800k+", labelEs: "$800k+" },
    ],
  },
  {
    intent: "buy",
    key: "preapproved",
    sortOrder: 3,
    type: "boolean",
    required: false,
    label: "Are you pre-approved for financing?",
    labelEs: "¿Tienes preaprobación de financiamiento?",
    options: [],
  },
  {
    intent: "buy",
    key: "also_selling",
    sortOrder: 5,
    type: "single_select",
    required: false,
    label: "Do you also need to sell a home?",
    labelEs: "¿También necesitas vender una propiedad?",
    options: [
      { value: "yes", label: "Yes", labelEs: "Sí" },
      { value: "no", label: "No", labelEs: "No" },
      { value: "unsure", label: "Not sure", labelEs: "No estoy seguro" },
    ],
  },
  {
    intent: "buy",
    key: "beds",
    sortOrder: 6,
    type: "number",
    required: false,
    label: "How many bedrooms do you need?",
    labelEs: "¿Cuántas habitaciones necesitas?",
    options: [],
  },
  // SELL
  {
    intent: "sell",
    key: "address",
    sortOrder: 1,
    type: "text",
    required: true,
    label: "What is the property address?",
    labelEs: "¿Cuál es la dirección de la propiedad?",
    options: [],
  },
  {
    intent: "sell",
    key: "timeline",
    sortOrder: 2,
    type: "single_select",
    required: true,
    label: "When do you want to sell?",
    labelEs: "¿Cuándo deseas vender?",
    options: [
      { value: "asap", label: "As soon as possible", labelEs: "Lo antes posible" },
      { value: "3_6", label: "3–6 months", labelEs: "3–6 meses" },
      { value: "exploring", label: "Exploring options", labelEs: "Explorando opciones" },
    ],
  },
  {
    intent: "sell",
    key: "occupancy",
    sortOrder: 3,
    type: "single_select",
    required: false,
    label: "Is the property currently occupied?",
    labelEs: "¿La propiedad está ocupada actualmente?",
    options: [
      { value: "owner", label: "Owner-occupied", labelEs: "Ocupada por el propietario" },
      { value: "tenant", label: "Tenant-occupied", labelEs: "Ocupada por inquilino" },
      { value: "vacant", label: "Vacant", labelEs: "Desocupada" },
    ],
  },
  // RENT
  {
    intent: "rent",
    key: "movein",
    sortOrder: 1,
    type: "single_select",
    required: true,
    label: "When do you need to move in?",
    labelEs: "¿Cuándo necesitas mudarte?",
    options: [
      { value: "0_1", label: "Within a month", labelEs: "Dentro de un mes" },
      { value: "1_3", label: "1–3 months", labelEs: "1–3 meses" },
    ],
  },
  {
    intent: "rent",
    key: "budget",
    sortOrder: 2,
    type: "single_select",
    required: true,
    label: "Monthly budget?",
    labelEs: "¿Presupuesto mensual?",
    options: [
      { value: "u2000", label: "Under $2,000", labelEs: "Menos de $2,000" },
      { value: "2000_3000", label: "$2,000–$3,000", labelEs: "$2,000–$3,000" },
      { value: "3000p", label: "$3,000+", labelEs: "$3,000+" },
    ],
  },
  {
    intent: "rent",
    key: "pets",
    sortOrder: 3,
    type: "boolean",
    required: false,
    label: "Do you have pets?",
    labelEs: "¿Tienes mascotas?",
    options: [],
  },
];
